version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t yyutong/around .
          docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
          docker push yyutong/around
